### ISSUE TITLE
如何求解两个轮子的速度

### ISSUE THREAD

**Issue by ralphoon** [ZevveZ/stm32_car#1]
您好，在项目中，您通过模糊决策算法求出小车的速度和应该旋转的角度后，是如果解析出两个轮子分别的速度的，这两句代码我有点不理解，可以帮忙解答一下吗？
    two_speed.speed1 = defuzzy_v + WHEEL_BASE * defuzzy_beta / (2 * DELTA_T);
    two_speed.speed0 = 2 * defuzzy_v - two_speed.speed1;

**Comment by ZevveZ** [comment]
不好意思，这个项目我已经不维护了，你自己理解一下吧
